sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
env:
  - DOCKER_VERSION=1.12.5
  - DOCKER_VERSION=1.11.1
  - DOCKER_VERSION=1.10.3
  - DOCKER_VERSION=1.9.1
  - DOCKER_VERSION=1.8.2
  - DOCKER_VERSION=1.7.1
matrix:
  fast_finish: true
before_install:
 - docker --version
 - gem install bundler
before_script:
 - sudo ./script/install_docker.sh ${DOCKER_VERSION}
 - uname -a
 - docker --version
 - docker info
