---
http_interactions:
- request:
    method: get
    uri: "<DOCKER_HOST>/v1.16/version"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Sun, 22 Nov 2015 04:15:29 GMT
      Content-Length:
      - '192'
    body:
      encoding: UTF-8
      string: |
        {"Version":"1.9.0","ApiVersion":"1.21","GitCommit":"76d6bc9","GoVersion":"go1.4.3","Os":"linux","Arch":"amd64","KernelVersion":"4.1.12-boot2docker","BuildTime":"Tue Nov  3 19:20:09 UTC 2015"}
    http_version: 
  recorded_at: Sun, 22 Nov 2015 04:15:28 GMT
recorded_with: VCR 2.9.2
